dist: xenial
language: python
python:
      - "3.6"
      - "3.7"
      - "3.8"
install:
      - pip install pillow
script:
      python dithering.py
notifications:
  irc:
    channels:
      - "irc.freenode.org#dithering"
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    on_success: never
    on_failure: always
  email: false

