dist: xenial

language: python

python:
      - "2.7"
      - "3.6"
      - "3.8"

install:
      - pip install -r requirements.txt

script:
      - python dithering.py

notifications:
  irc:
    channels:
      - "irc.freenode.org#dithering"
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    on_success: always #was nevers
    on_failure: always
  email: false
