dist: trusty
language: python
python:
      - "3.6"
install:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
script:
      python Dithering.py
notifications:
  irc:
    channels: "irc.freenode.org#dithering"
    template:
      - "%{repository_name}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email: false

